Add translations json file for bulgarian (bg)
RobertD502/home-assistant-petkit pull request #42
Opened 2023-09-25 15:46 UTC by lachezar-gizdov

translate from the en.json file all the values to Bulgarian (BG).

2023-09-25 16:00 UTC, RobertD502 requested changes

2023-09-25 16:00 UTC, RobertD502 commented on custom_components/petkit/translations/bg.json
> +      "timezone_error": "Часовата зона не може да бъде намерена. Ако използвате Home Assistant като самостоятелен Docker контейнер, трябва да дефинирате променливата TZ."
Please look at the current en.json file, the timezone_error was updated before the last release.

2023-09-25 16:00 UTC, RobertD502 commented on custom_components/petkit/translations/bg.json
> +          "polling_interval": "Интервал на опитване (секунди)"
Please look at the current en.json file, a `timezone` key exists here now.

2023-09-25 16:00 UTC, RobertD502 commented on custom_components/petkit/translations/bg.json
> +          "polling_interval": "Интервал на опитване (секунди)"
Please look at the current en.json file, a `timezone` key exists here now.

2023-09-25 16:00 UTC, RobertD502 commented on custom_components/petkit/translations/bg.json
> +          "polling_interval": "Интервал на опитване (секунди)"
Please look at the current en.json file, a `timezone` key exists here now.

2023-09-25 16:00 UTC, RobertD502 commented on custom_components/petkit/translations/bg.json
> +        "name": "Dispensed hopper 2"
Did you miss this translation?

2023-09-26 05:54 UTC, lachezar-gizdov commented on custom_components/petkit/translations/bg.json
> +        "name": "Dispensed hopper 2"
yes, fixed.

2023-09-26 16:14 UTC, RobertD502 approved these changes
Thanks!

2023-09-26 16:17 UTC, merged